<a href="https://colab.research.google.com/github/darwinyusef/TallerPandasAnalitica/blob/master/movies_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
movies = pd.read_csv('movies.csv')
movies

,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,758323,The Pope's Exorcist,2023-04-05,"['Horror', 'Mystery', 'Thriller']",English,7.4,619,5089.969,"Father Gabriele Amorth, Chief Exorcist of the ...",18000000,"['Screen Gems', '2.0 Entertainment', 'Jesus & ...",65675816,103,Inspired by the actual files of Father Gabriel...
1,640146,Ant-Man and the Wasp: Quantumania,2023-02-15,"['Action', 'Adventure', 'Science Fiction']",English,6.6,2294,4665.438,Super-Hero partners Scott Lang and Hope van Dy...,200000000,"['Marvel Studios', 'Kevin Feige Productions']",464566092,125,Witness the beginning of a new dynasty.
2,502356,The Super Mario Bros. Movie,2023-04-05,"['Animation', 'Adventure', 'Family', 'Fantasy'...",English,7.5,1861,3935.550,"While working underground to fix a water main,...",100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1121048165,92,NaN
3,868759,Ghosted,2023-04-18,"['Action', 'Comedy', 'Romance']",English,7.2,652,2791.532,Salt-of-the-earth Cole falls head over heels f...,0,"['Skydance Media', 'Apple Studios']",0,120,Finding that special someone can be a real adv...
4,594767,Shazam! Fury of the Gods,2023-03-15,"['Action', 'Comedy', 'Fantasy', 'Adventure']",English,6.8,1510,2702.593,"Billy Batson and his foster siblings, who tran...",125000000,"['New Line Cinema', 'The Safran Company', 'DC ...",133437105,130,Oh. My. Gods.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,374473,"I, Daniel Blake",2016-10-21,['Drama'],English,7.7,1220,10.774,"A middle aged carpenter, who requires state we...",0,"['Why Not Productions', 'Wild Bunch', 'Sixteen...",15793051,100,NaN
9996,16774,Hellboy Animated: Sword of Storms,2006-10-28,"['TV Movie', 'Fantasy', 'Animation', 'Action',...",English,6.3,99,12.739,A folklore professor becomes unwittingly posse...,0,"['IDT Entertainment', 'Film Roman']",0,73,NaN
9997,13564,Return to House on Haunted Hill,2007-10-03,"['Horror', 'Thriller']",English,5.6,263,12.769,Eight years have passed since Sara Wolfe and E...,0,"['Dark Castle Entertainment', 'Warner Premiere']",0,81,NaN
9998,482204,My Sister-in-law's Job,2017-08-31,"['Drama', 'Romance']",Korean,5.0,5,10.425,An erotic film that depicts the dangerous rela...,0,[],0,89,NaN
9999,444539,The Bookshop,2017-11-10,['Drama'],English,6.5,382,12.525,"Set in a small English town in 1959, a woman d...",5400000,"['Zephyr Films', 'A Contracorriente Films', 'D...",12055868,110,A town that lacks a bookshop isn't always a to...

In [ ]:
movies.shape

(10000, 14)

In [ ]:
movies[['id', 'title', 'genres']]

,id,title,genres
0,758323,The Pope's Exorcist,"['Horror', 'Mystery', 'Thriller']"
1,640146,Ant-Man and the Wasp: Quantumania,"['Action', 'Adventure', 'Science Fiction']"
2,502356,The Super Mario Bros. Movie,"['Animation', 'Adventure', 'Family', 'Fantasy'..."
3,868759,Ghosted,"['Action', 'Comedy', 'Romance']"
4,594767,Shazam! Fury of the Gods,"['Action', 'Comedy', 'Fantasy', 'Adventure']"
...,...,...,...
9995,374473,"I, Daniel Blake",['Drama']
9996,16774,Hellboy Animated: Sword of Storms,"['TV Movie', 'Fantasy', 'Animation', 'Action',..."
9997,13564,Return to House on Haunted Hill,"['Horror', 'Thriller']"
9998,482204,My Sister-in-law's Job,"['Drama', 'Romance']"
9999,444539,The Bookshop,['Drama']

In [ ]:
movies.head()

,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,758323,The Pope's Exorcist,2023-04-05,"['Horror', 'Mystery', 'Thriller']",English,7.4,619,5089.969,"Father Gabriele Amorth, Chief Exorcist of the ...",18000000,"['Screen Gems', '2.0 Entertainment', 'Jesus & ...",65675816,103,Inspired by the actual files of Father Gabriel...
1,640146,Ant-Man and the Wasp: Quantumania,2023-02-15,"['Action', 'Adventure', 'Science Fiction']",English,6.6,2294,4665.438,Super-Hero partners Scott Lang and Hope van Dy...,200000000,"['Marvel Studios', 'Kevin Feige Productions']",464566092,125,Witness the beginning of a new dynasty.
2,502356,The Super Mario Bros. Movie,2023-04-05,"['Animation', 'Adventure', 'Family', 'Fantasy'...",English,7.5,1861,3935.550,"While working underground to fix a water main,...",100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1121048165,92,NaN
3,868759,Ghosted,2023-04-18,"['Action', 'Comedy', 'Romance']",English,7.2,652,2791.532,Salt-of-the-earth Cole falls head over heels f...,0,"['Skydance Media', 'Apple Studios']",0,120,Finding that special someone can be a real adv...
4,594767,Shazam! Fury of the Gods,2023-03-15,"['Action', 'Comedy', 'Fantasy', 'Adventure']",English,6.8,1510,2702.593,"Billy Batson and his foster siblings, who tran...",125000000,"['New Line Cinema', 'The Safran Company', 'DC ...",133437105,130,Oh. My. Gods.

In [ ]:
movies.tail()

,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
9995,374473,"I, Daniel Blake",2016-10-21,['Drama'],English,7.7,1220,10.774,"A middle aged carpenter, who requires state we...",0,"['Why Not Productions', 'Wild Bunch', 'Sixteen...",15793051,100,NaN
9996,16774,Hellboy Animated: Sword of Storms,2006-10-28,"['TV Movie', 'Fantasy', 'Animation', 'Action',...",English,6.3,99,12.739,A folklore professor becomes unwittingly posse...,0,"['IDT Entertainment', 'Film Roman']",0,73,NaN
9997,13564,Return to House on Haunted Hill,2007-10-03,"['Horror', 'Thriller']",English,5.6,263,12.769,Eight years have passed since Sara Wolfe and E...,0,"['Dark Castle Entertainment', 'Warner Premiere']",0,81,NaN
9998,482204,My Sister-in-law's Job,2017-08-31,"['Drama', 'Romance']",Korean,5.0,5,10.425,An erotic film that depicts the dangerous rela...,0,[],0,89,NaN
9999,444539,The Bookshop,2017-11-10,['Drama'],English,6.5,382,12.525,"Set in a small English town in 1959, a woman d...",5400000,"['Zephyr Films', 'A Contracorriente Films', 'D...",12055868,110,A town that lacks a bookshop isn't always a to...

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10000 non-null  int64
 1   title                 10000 non-null  object
 2   release_date          9979 non-null   object
 3   genres                10000 non-null  object
 4   original_language     10000 non-null  object
 5   vote_average          10000 non-null  float64
 6   vote_count            10000 non-null  int64
 7   popularity            10000 non-null  float64
 8   overview              9923 non-null   object
 9   budget                10000 non-null  int64
 10  production_companies  10000 non-null  object
 11  revenue               10000 non-null  int64
 12  runtime               10000 non-null  int64
 13  tagline               7241 non-null   object
dtypes: float64(2), int64(5), object(7)
memory usage: 1.1+ MB

In [ ]:
movies.popularity.value_counts(ascending=True)

5089.969    1
17.808      1
16.759      1
16.810      1
16.060      1
           ..
11.625      5
14.668      5
13.898      5
12.037      5
12.698      5
Name: popularity, Length: 8290, dtype: int64

In [ ]:
movies.vote_count.value_counts(ascending=True)

742       1
3633      1
3525      1
3435      1
5555      1
       ...
4        71
3        84
1        99
2       103
0       248
Name: vote_count, Length: 3447, dtype: int64

In [ ]:
movies.vote_average.value_counts(ascending=True)

9.3      1
9.2      1
9.5      1
2.2      1
8.8      1
      ...
6.7    420
6.9    421
6.3    428
6.5    431
6.8    461
Name: vote_average, Length: 74, dtype: int64